FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY tests ./tests

CMD ["python", "-c", "import os, sys; print('PWD:', os.getcwd()); print('PYTHONPATH:', os.environ.get('PYTHONPATH')); print('SYS.PATH:', sys.path); print('FILES:', os.listdir('/app')); import app.main; print('IMPORT SUCCESS')"]